{{ if .Values.ingress | default false }}
{{ if .Values.ingress.enabled | default false }}
{{ if .Values.ingress.basicAuth | default false }}
{{ if .Values.ingress.basicAuth.enabled | default false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-basic-auth
  namespace: {{ .Values.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: "Opaque"
data:
  {{/* htpasswd is available since helm@3.2.0 */}}
  auth: {{ htpasswd .Values.ingress.basicAuth.username .Values.ingress.basicAuth.password | b64enc | quote }}
{{ end }}
{{ end }}
{{ end }}
{{ end }}
