profile = { default = { libs = ["node_modules", "lib"] } }
[default]
src = "contracts"           
out = "out"                 
libs = ["node_modules"]     
solc_version = "0.8.26"     
test = "test-foundry"
gas_price = 10
