apiVersion: v1
kind: Secret
metadata:
  name: githubs-actions-token
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: github-actions-sa
type: kubernetes.io/service-account-token
