apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-binding
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: github-actions-sa
  namespace: monitoring
roleRef:
  kind: Role
  name: github-actions-role
  apiGroup: rbac.authorization.k8s.io
