apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: diaoracleservice-conduit-011
  namespace: monitoring
spec:
  itemPath: "vaults/hetzner-tofu-cluster-1/items/diaoracleservice-conduit-011"