apiVersion: v1
kind: Secret
metadata:
  name: github-deploy-sa-prod-token
  namespace: dia-oracles-prod
  annotations:
    kubernetes.io/service-account.name: github-deploy-sa-prod
type: kubernetes.io/service-account-token
