apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dia-lumina
  name: github-deploy-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create", "delete", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "delete", "update", "patch"]
