name: diaoracleservice-conduit-011
version: "v1.0.0"
namespace: dia-oracles-prod
replicaCount: 1
repository:
  image: "us.icr.io/dia-registry/oracles/diadecentraloracleservice"
  tag:
  pullPolicy: "Always"
imagePullSecrets:
  - name: all-icr-io
app:
  resources:
    requests:
      memory: 250Mi
      cpu: "0.1"
    limits:
      memory: 300Mi
      cpu: "0.15"
  affinity:
    enabled: true
    workergroup:
      - default
      - default-alternative
  env:
    - name: PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          name: diaoracleservice-conduit-011
          key: .privatekey
    - name: PRIVATE_KEY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: diaoracleservice-conduit-011
          key: .password
    - name: DEPLOYED_CONTRACT
      value: "0x4d6c5b3796b1564307cb6dc37928f2494c8dcd6e"
    - name: BLOCKCHAIN_NODE
      value: "https://rpc-static-violet-vicuna-qhcog2uell.t.conduit.xyz"
    - name: BACKUP_NODE
      value: "https://rpc-static-violet-vicuna-qhcog2uell.t.conduit.xyz"
    - name: CHAIN_ID
      value: "23104"
    - name: FREQUENCY_SECONDS
      value: "30"
    - name: EXCHANGEPAIRS
      value: "
      Binance:BTC-USDT,
      Binance:ETH-USDT,
      Binance:WIF-USDT,
      Binance:ENS-USDT,
      Binance:YFI-USDT,
      Binance:STORJ-USDT,
      Binance:SUSHI-USDT,
      Binance:MOVR-USDT,
      Binance:STG-USDT,
      Binance:DIA-USDT,
      Binance:OMG-USDT,
      Binance:USDC-USDT,
      GateIO:BTC-USDT,
      GateIO:ETH-USDT,
      GateIO:WIF-USDT,
      GateIO:ENS-USDT,
      GateIO:YFI-USDT,
      GateIO:STORJ-USDT,
      GateIO:SUSHI-USDT,
      GateIO:MOVR-USDT,
      GateIO:STG-USDT,
      GateIO:DIA-USDT,
      GateIO:OMG-USDT,
      GateIO:USDC-USDT,
      KuCoin:BTC-USDT,
      KuCoin:ETH-USDT,
      KuCoin:WIF-USDT,
      KuCoin:ENS-USDT,
      KuCoin:YFI-USDT,
      KuCoin:STORJ-USDT,
      KuCoin:SUSHI-USDT,
      KuCoin:MOVR-USDT,
      KuCoin:STG-USDT,
      KuCoin:DIA-USDT,
      KuCoin:OMG-USDT,
      KuCoin:USDC-USDT,
      Crypto.com:BTC-USDT,
      Crypto.com:ETH-USDT,
      Crypto.com:WIF-USDT,
      Crypto.com:ENS-USDT,
      Crypto.com:YFI-USDT,
      Crypto.com:STORJ-USDT,
      Crypto.com:SUSHI-USDT,
      Crypto.com:MOVR-USDT,
      Crypto.com:STG-USDT,
      Crypto.com:DIA-USDT,
      Crypto.com:OMG-USDT,
      Crypto.com:USDC-USDT,
      Kraken:BTC-USDT,
      Kraken:ETH-USDT,
      Kraken:WIF-USDT,
      Kraken:ENS-USDT,
      Kraken:YFI-USDT,
      Kraken:STORJ-USDT,
      Kraken:SUSHI-USDT,
      Kraken:MOVR-USDT,
      Kraken:STG-USDT,
      Kraken:OMG-USDT,
      Kraken:USDC-USDT,
      CoinBase:BTC-USDT,
      CoinBase:ETH-USDT,
      CoinBase:ENS-USDT,
      CoinBase:YFI-USDT,
      CoinBase:STORJ-USDT,
      CoinBase:SUSHI-USDT,
      CoinBase:STG-USDT,
      CoinBase:DIA-USDT
      "
    - name: UniswapV2_URI_REST
      value: "https://ethereum-mainnet.core.chainstack.com/d8d52f82b117f60a2b73473fca94c0f6"
    - name: UniswapV2_URI_WS
      value: "wss://ethereum-mainnet.core.chainstack.com/d8d52f82b117f60a2b73473fca94c0f6"
    - name: POOLS
      value: "UniswapV2:0x0d4a11d5EEaaC28EC3F61d100daF4d40471f1852:0,UniswapV2:0xc5be99A02C6857f9Eac67BbCE58DF5572498F40c:0"
    - name: HTTPS_PROXY
      value: "http://samuelbrack:hD3bfFBVLg@185.13.225.52:50100"
service:
  enabled: false
  type: "ClusterIP"
  ports: []
persistence:
  enabled: false
