name: decentralized-feeder-release-pipeline

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  deployments: write
  id-token: none

jobs:
  push_images:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Get release tag
      - name: Get Release Tag
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/tags/}
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      # Install IBM Cloud CLI and Container Registry CLI
      - name: Install IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud plugin install container-registry -f

      # Log in to IBM Cloud
      - name: Log in to IBM Cloud
        env:
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
        run: |
          ibmcloud login --apikey $IBM_CLOUD_API_KEY --no-region
          ibmcloud target -r us-south
          ibmcloud target -g Default

      # Build and Tag Docker images for IBM Cloud Registry
      - name: Build and Tag Docker images
        run: |
          docker build -f build/Dockerfile-luminaScraperFeeder -t us.icr.io/dia-registry/oracles/diadecentraloracleservice:${{ env.RELEASE_TAG }} .
          docker build -f build/Dockerfile-luminaSimulationFeeder -t us.icr.io/dia-registry/oracles/luminasimulationfeeder:${{ env.RELEASE_TAG }} .

      # Push Docker images to IBM Cloud Registry
      - name: Push Docker images to IBM Cloud Registry
        run: |
          ibmcloud cr login
          docker push us.icr.io/dia-registry/oracles/diadecentraloracleservice:${{ env.RELEASE_TAG }}
          docker push us.icr.io/dia-registry/oracles/luminasimulationfeeder:${{ env.RELEASE_TAG }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Extract semantic version (remove 'v' prefix)
      - name: Set SemVer tag
        run: |
          SEMVER_TAG=${RELEASE_TAG#v}
          echo "SEMVER_TAG=$SEMVER_TAG" >> $GITHUB_ENV

      # Build & push multi-arch scraper to Docker Hub
      - name: Build & Push Decentralized Feeder Scraper Multi-arch to Docker Hub
        uses: docker/build-push-action@v4
        timeout-minutes: 30
        with:
          context: .
          file: build/Dockerfile-luminaScraperFeeder
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            diadata/decentralized-feeder:${{ env.SEMVER_TAG }}
            diadata/decentralized-feeder:scraper-${{ env.SEMVER_TAG }}
            ${{ !contains(env.SEMVER_TAG, '-') && 'diadata/decentralized-feeder:latest' || '' }}
            ${{ !contains(env.SEMVER_TAG, '-') && 'diadata/decentralized-feeder:scraper-latest' || '' }} 
          cache-from: type=registry,ref=diadata/decentralized-feeder:buildcache
          cache-to: type=registry,ref=diadata/decentralized-feeder:buildcache,mode=max

      # Logout and cleanup
      - name: Logout and cleanup
        run: |
          docker logout
          ibmcloud logout 